config/routes.rb
CHOPFinal::Application.routes.draw do
  get "profiles/show"

  devise_for :users

  resources :snps

  root :to => "home#index"

  get '/:id', to: 'profiles#show'

end

app/models/snp.rb
class Snp < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :profile_name, :institution
  
  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                             with: /[a-zA-Z0-9_-]+/,
                             message: 'Must be formatted correctly.'
                           }

  has_many :snps

  def full_name
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params(:id))
  	if @user
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/controllers/snps_controller.rb
class SnpsController < ApplicationController
  # GET /snps
  # GET /snps.json
  def index
    @snps = Snp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snps }
    end
  end

  # GET /snps/1
  # GET /snps/1.json
  def show
    @snp = Snp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snp }
    end
  end

  # GET /snps/new
  # GET /snps/new.json
  def new
    @snp = Snp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snp }
    end
  end

  # GET /snps/1/edit
  def edit
    @snp = Snp.find(params[:id])
  end

  # POST /snps
  # POST /snps.json
  def create
    @snp = Snp.new(params[:snp])

    respond_to do |format|
      if @snp.save
        format.html { redirect_to @snp, notice: 'Snp was successfully created.' }
        format.json { render json: @snp, status: :created, location: @snp }
      else
        format.html { render action: "new" }
        format.json { render json: @snp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snps/1
  # PUT /snps/1.json
  def update
    @snp = Snp.find(params[:id])

    respond_to do |format|
      if @snp.update_attributes(params[:snp])
        format.html { redirect_to @snp, notice: 'Snp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snps/1
  # DELETE /snps/1.json
  def destroy
    @snp = Snp.find(params[:id])
    @snp.destroy

    respond_to do |format|
      format.html { redirect_to snps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sn_ps_helper.rb
module SnPsHelper
end

app/views/home/index.html.erb
<h1>Welcome to the Organ Transplant Website</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum, risus eget ultricies dapibus, risus purus pharetra felis, non bibendum eros urna a neque. Cras a dignissim neque. Integer blandit convallis tortor, eget lobortis diam tempus at. Mauris purus urna, tempus vel convallis et, euismod in orci. Suspendisse eu libero nec ipsum vestibulum adipiscing quis vel turpis. Maecenas in mi eget quam ullamcorper vehicula. Integer magna urna, aliquam sed ultrices ac, iaculis sit amet odio. Morbi eu justo id nibh accumsan fermentum. Pellentesque iaculis varius mauris, ut gravida lectus molestie id. Vivamus nec nunc ac quam consequat elementum non vel ante. Duis odio purus, viverra ac condimentum ut, interdum in sem. Aliquam erat volutpat. Nulla at eros congue arcu lacinia rutrum ut ac augue. Vivamus ac ante ut risus hendrerit consectetur ut a turpis.

Nulla luctus mollis quam, eu convallis mi suscipit in. Aliquam porta lacus ac metus accumsan facilisis. Etiam nunc nisl, vestibulum a pellentesque non, egestas nec nulla. Praesent posuere, felis et tincidunt auctor, urna urna congue est, in semper quam enim pharetra augue. Cras ultrices faucibus blandit. Phasellus iaculis ante sed dolor aliquet consequat. Cras tincidunt rhoncus mollis.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla facilisi. Suspendisse potenti. Etiam facilisis nisi eget lorem bibendum non lacinia lectus convallis. Maecenas quis turpis sed magna tincidunt sagittis. Vivamus ac massa suscipit leo feugiat venenatis posuere aliquet odio. Sed porta iaculis magna blandit eleifend. Donec pharetra commodo sem. Sed tellus nisl, tincidunt nec pellentesque id, aliquet non nunc. Donec non mattis enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque mattis magna sed diam vulputate in rutrum velit viverra. Phasellus scelerisque malesuada sapien, vel dignissim dolor malesuada id.

Donec sodales, nisl sit amet aliquet mattis, erat nunc blandit quam, sodales porttitor elit sem at metus. Duis sodales porta mi id facilisis. Nullam iaculis, erat at dictum suscipit, odio metus ornare urna, in bibendum lectus orci ac arcu. Nam venenatis elementum lorem, ultrices hendrerit orci congue id. Proin pellentesque dolor quis mauris tincidunt sit amet porttitor mauris viverra. Ut facilisis, odio id pellentesque dictum, ante metus pulvinar lectus, ut vulputate magna elit et urna. Maecenas tincidunt est varius eros pharetra ut placerat nisl consequat. Aenean mollis purus non elit euismod ultrices. Praesent quis nunc metus. Suspendisse potenti.
</p>
<a href="/users/sign_up" class="btn btn-primary btn-large">Sign Up</a>
<a href="/users/sign_in" class="btn btn-primary btn-large">Log-In</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CHOP -- Organ Transplant SNP Database</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">CHOP -- Organ Transplant SNP Database</a>
    <ul class="nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="http://www.chop.edu/">LINK 1</a></li>
      <li class="divider-vertical"></li>
      <li><a href="http://www.ncbi.nlm.nih.gov/">LINK 2</a></li>
      <li class="divider-vertical"></li>
      <li><a href="http://genome.ucsc.edu/">LINK 3</a></li>
      <li class="divider-vertical"></li>
      <li><a href="http://www.ncbi.nlm.nih.gov/projects/SNP/">LINK 4</a></li>
      <li class="divider-vertical"></li>
    </ul>
    <ul class ="nav pull-right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.first_name + " " + current_user.last_name, edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Register", new_user_registration_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>


	<div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button class="close" data-dismiss="alert">x</button>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-error">
        <button class="close" data-dismiss="alert">x</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
	
	</div>
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name %></h1>
</div>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc tortor, auctor ac facilisis eu, volutpat ut nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In vulputate sem quis lacus posuere, et gravida libero porta. Cras rhoncus dictum arcu id faucibus. Fusce non cursus urna, a sollicitudin tellus. Donec tincidunt sodales odio vel tincidunt. Quisque quis sem in felis faucibus condimentum a id elit. Vivamus congue sodales metus, nec condimentum nisl. Ut sed vulputate sem, eu aliquam orci.
<p>
Vivamus pharetra id orci vitae condimentum. Duis sed arcu nunc. Maecenas libero diam, sollicitudin in convallis rhoncus, feugiat et mauris. Nulla porta orci eu tellus gravida rutrum. Sed pellentesque mi eget eleifend fringilla. Phasellus mi eros, dictum ac augue eu, tristique porttitor turpis. Quisque mattis ornare nulla ut faucibus. Phasellus scelerisque tortor eget mauris gravida aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis vel dui magna. Donec non lacus quis neque condimentum semper. Pellentesque ac nibh et nibh malesuada semper. Maecenas porta mi enim, a suscipit velit dapibus vitae. Aenean in laoreet nunc.
<p>
Duis nec vehicula libero. Nullam eu tortor sapien. In id nisl vestibulum, mattis arcu eget, lobortis diam. Sed sed placerat purus. Donec tincidunt elit in varius congue. Quisque in cursus nisl, eu ultricies sapien. Sed congue massa non mollis tincidunt. Fusce mauris urna, luctus pulvinar augue vel, hendrerit ultrices nisi.
<p>
Aenean eget sem felis. In ut turpis arcu. Donec dapibus felis quis tristique vehicula. Sed fringilla posuere nisi quis vehicula. Aliquam consectetur eros a diam sagittis adipiscing. Mauris pellentesque velit convallis pharetra mattis. Pellentesque sed justo vel augue tincidunt scelerisque at id urna. Ut adipiscing, mauris in dictum venenatis, magna odio varius mauris, non pretium diam velit a odio. Vestibulum bibendum egestas diam, eu bibendum velit ornare in. Donec rutrum consequat metus, non aliquet mi posuere quis.
<p>
Vivamus nisi nisi, placerat pretium lacinia id, eleifend et justo. Duis quam arcu, dignissim quis lacus vitae, pulvinar congue erat. Nam vel eleifend justo, consectetur consequat lacus. Vivamus lobortis augue quis lacus consectetur, at molestie odio ornare. Duis et malesuada lectus. Maecenas a felis sem. Donec ante tellus, viverra eu bibendum eget, facilisis non odio. Aenean sit amet lorem mollis, ullamcorper velit ac, mollis lectus. Aliquam varius volutpat blandit. In scelerisque scelerisque metus, id varius dui dapibus et. Curabitur auctor erat orci, et cursus ligula scelerisque quis.

app/views/snps/_form.html.erb
<%= simple_form_for(@snp, html: {class: "form-horizontal"}) do |f| %>
  <% if @snp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snp.errors.count, "error") %> prohibited this snp from being saved:</h2>

      <ul>
      <% @snp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.input :name %>
<%= f.input :content %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/snps/edit.html.erb
<h1>Editing snp</h1>

<%= render 'form' %>

<%= link_to 'Show', @snp %> |
<%= link_to 'Back', snps_path %>

app/views/snps/new.html.erb
<h1>New snp</h1>

<%= render 'form' %>

<%= link_to 'Back', snps_path %>

app/views/snps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @snp.name %>
</p>

<p>
  <b>Content:</b>
  <%= @snp.content %>
</p>


<%= link_to 'Edit', edit_snp_path(@snp) %> |
<%= link_to 'Back', snps_path %>